# Generated by Django 5.1.6 on 2025-02-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='features',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fraud_probability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='top_contributing_features',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
